Gh pages 7.13 test release branch creation Team PSD Manual Update
lzim/teampsd pull request #2830
Opened 2023-01-07 19:27 UTC by jamesmrollins

- Added instructions for test_version_release branch creation.
- Added a Readme.md in the actions folder to explain what the actions do.
- Added images to support user instructions.
- Updated _bookdown.yml to include new subchapter listing in TeamPSD manual

2023-02-02 18:12 UTC, epearman requested changes
@jamesmrollins, @emilymetcalf114 and I have reviewed these directions and made some change requests. We have not yet tested the actual function of the test branch yml because we are still a little unclear on some of the directions as we noted here.

2023-02-02 18:12 UTC, epearman commented on 7.13_test_release_branch_creation.md
> +- "x_x" indicates the current release and the future release.
Do what we enter for x_x need to match any of the code in the yaml file for it to work or is what we enter for x_x arbitrary and for naming convention/tracking purposes only.

2023-05-18 15:55 UTC, ljmoody reviewed
@epearman @emilymetcalf114 - Please see my comments and suggested changes based on your feedback and let me know your thoughts. 
FYI @jamesmrollins.

2023-05-18 15:55 UTC, ljmoody reviewed
@epearman @emilymetcalf114 - Please see my comments and suggested changes based on your feedback and let me know your thoughts. 
FYI @jamesmrollins.

2023-05-19 18:35 UTC, epearman approved these changes

2023-05-19 18:36 UTC, merged